name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

  train-and-quantize:
    needs: test-suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Train and Quantize
        run: |
          pip install -r requirements.txt
          python src/train.py
          python src/quantize.py

  build-and-test-container:
    needs: train-and-quantize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t mlops-lr .
      - name: Run Container
        run: docker run --rm mlops-lr
